#
###################################
# Site wide configuration
####################################
#
title: ssunno
email: lsn3192@gmail.com
description: A simple blog powered by jekyll.
url: https://ssunno.github.io # the base hostname & protocol for your site
keywords: ["ssunno"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: "<!-- more -->"
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: ssunno
  avatar: 8bit.png
  job: "Researcher"
  bio: "Software engineering & Computer Vision using Deep Learning."
  email: lsn3192@gmail.com
  disqus-shortname:
  twitter:  #username
  facebook: ssunnohd #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ssunno #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: 선로-이-2734a9144 #username
  xing: #username
  instagram: ssunno #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
